server {
    listen 80;
    server_name localhost;

    # Root directory onde os estáticos do React/Vite foram transferidos
    root /usr/share/nginx/html;
    index index.html;

    # Fallback Routing SPA React Router
    # Toda rota não lida no disco fisicamente (arquivos e pastas) redireciona de volta ao index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desabilitar logs de acesso para assets estáticos e aplicar cache de longo prazo
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires max;
        log_not_found off;
    }

    # Opcional: Proxy para API (Evita CORS se for colocar no mesmo container futuramente, mas hoje VITE_API_URL via host docker lida com isso)
    # location /api/ {
    #     proxy_pass http://api:3000/;
    # }
}
